apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2021-06-19T05:57:03Z"
    labels:
      endpointslice.kubernetes.io/skip-mirror: "true"
    name: kubernetes
    namespace: default
    resourceVersion: "208"
    uid: 5e988d9f-bbf6-4ce2-9b21-15f36c0393a3
  subsets:
  - addresses:
    - ip: 192.168.49.2
    ports:
    - name: https
      port: 8443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2021-06-21T02:31:58Z"
    creationTimestamp: "2021-06-21T02:29:36Z"
    labels:
      id: earth-2x3-api-svc
    name: earth-2x3-api-svc
    namespace: earth
    resourceVersion: "2118"
    uid: e964c720-335f-486a-84fa-af729f03c933
  subsets:
  - addresses:
    - ip: 172.17.0.24
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-2x3-api-686fc9cb8f-xr9xr
        namespace: earth
        resourceVersion: "2053"
        uid: 9cac3514-caeb-4e5d-8e43-e2fe22028a06
    - ip: 172.17.0.29
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-2x3-api-686fc9cb8f-ws82x
        namespace: earth
        resourceVersion: "2103"
        uid: 25217208-8d7d-4bc2-8fa5-4e642d4ff706
    - ip: 172.17.0.30
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-2x3-api-686fc9cb8f-pnqnl
        namespace: earth
        resourceVersion: "2116"
        uid: bba76961-d358-4be5-8e7a-874cd1023fae
    ports:
    - name: 4546-80
      port: 80
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2021-06-21T02:32:36Z"
    creationTimestamp: "2021-06-21T02:29:36Z"
    labels:
      id: earth-2x3-web-svc
    name: earth-2x3-web-svc
    namespace: earth
    resourceVersion: "2215"
    uid: 0a3e433d-6fe0-477a-ad34-9cdc258d27e3
  subsets:
  - addresses:
    - ip: 172.17.0.28
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-2x3-web-569bc6cdb7-92t2f
        namespace: earth
        resourceVersion: "2089"
        uid: 0734d918-89fe-4561-95c0-fd2137d9f1b8
    - ip: 172.17.0.32
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-2x3-web-569bc6cdb7-gvgqm
        namespace: earth
        resourceVersion: "2137"
        uid: f10670ab-a358-4b14-9d29-18edfacc63cc
    - ip: 172.17.0.34
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-2x3-web-569bc6cdb7-68s9j
        namespace: earth
        resourceVersion: "2154"
        uid: 71fa242f-b181-4773-b4c7-0c1d8fafdf25
    - ip: 172.17.0.37
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-2x3-web-569bc6cdb7-wdnjf
        namespace: earth
        resourceVersion: "2182"
        uid: 4b889b14-ead9-4b0c-9a91-e287a2bedfa1
    - ip: 172.17.0.38
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-2x3-web-569bc6cdb7-w8kg8
        namespace: earth
        resourceVersion: "2194"
        uid: 1d17dc64-6b62-40e9-804b-51b8bdf3b74b
    - ip: 172.17.0.40
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-2x3-web-569bc6cdb7-mqlzp
        namespace: earth
        resourceVersion: "2212"
        uid: 16b39603-0a55-47c1-bc30-5b5e879e3ece
    ports:
    - name: 4545-80
      port: 80
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: "2021-06-21T02:29:36Z"
    labels:
      id: earth-3cc-web
    name: earth-3cc-web
    namespace: earth
    resourceVersion: "2264"
    uid: 819a22f7-8153-4f8a-a76a-330d1f88e963
  subsets:
  - notReadyAddresses:
    - ip: 172.17.0.42
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-3cc-web-789c6dddc7-vc2f2
        namespace: earth
        resourceVersion: "2231"
        uid: c76287ab-73d0-4dcf-ac0b-dc1ed8503983
    - ip: 172.17.0.43
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-3cc-web-789c6dddc7-bf8hf
        namespace: earth
        resourceVersion: "2239"
        uid: 00813324-ed52-46c5-870c-9f4fac4ca23b
    - ip: 172.17.0.44
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-3cc-web-789c6dddc7-h9ths
        namespace: earth
        resourceVersion: "2251"
        uid: 53d63452-7dd0-498e-aef3-57e186eca32d
    - ip: 172.17.0.45
      nodeName: minikube
      targetRef:
        kind: Pod
        name: earth-3cc-web-789c6dddc7-wfgtt
        namespace: earth
        resourceVersion: "2263"
        uid: 545043f0-4c3d-4cf8-8103-74e83306ff00
    ports:
    - name: 6363-80
      port: 80
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2021-06-21T02:33:26Z"
    creationTimestamp: "2021-06-21T02:29:36Z"
    name: jupiter-crew-svc
    namespace: jupiter
    resourceVersion: "2310"
    uid: 407e0326-eef4-4cb0-9148-ababfd230411
  subsets:
  - addresses:
    - ip: 172.17.0.49
      nodeName: minikube
      targetRef:
        kind: Pod
        name: jupiter-crew-deploy-6785c47f64-rstg5
        namespace: jupiter
        resourceVersion: "2308"
        uid: fd8388f2-38cc-4344-9f67-00a9bc54de25
    ports:
    - name: 8080-80
      port: 80
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      control-plane.alpha.kubernetes.io/leader: '{"holderIdentity":"minikube_8f81080e-4965-4c78-aea1-4407b2a19ae5","leaseDurationSeconds":15,"acquireTime":"2021-06-21T02:29:56Z","renewTime":"2021-06-21T03:24:50Z","leaderTransitions":1}'
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Endpoints","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"k8s.io-minikube-hostpath","namespace":"kube-system"}}
    creationTimestamp: "2021-06-19T05:57:58Z"
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
    name: k8s.io-minikube-hostpath
    namespace: kube-system
    resourceVersion: "4952"
    uid: 38e10edb-571c-441c-a7eb-506fa8ab5994
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2021-06-21T02:29:32Z"
    creationTimestamp: "2021-06-19T05:57:24Z"
    labels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: CoreDNS
    name: kube-dns
    namespace: kube-system
    resourceVersion: "1185"
    uid: b689301d-07eb-4398-a3c1-fd9b735a37a0
  subsets:
  - addresses:
    - ip: 172.17.0.2
      nodeName: minikube
      targetRef:
        kind: Pod
        name: coredns-558bd4d5db-cw84c
        namespace: kube-system
        resourceVersion: "1183"
        uid: a99dcc20-6039-475a-b371-83bccf6b2dea
    ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
    - name: dns
      port: 53
      protocol: UDP
    - name: metrics
      port: 9153
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2021-06-21T02:29:36Z"
    creationTimestamp: "2021-06-21T02:29:36Z"
    labels:
      app: manager-api-svc
    name: manager-api-svc
    namespace: mars
    resourceVersion: "1333"
    uid: 653d704f-174a-46fe-86e7-3e12d6a7c30d
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2021-06-21T02:33:51Z"
    creationTimestamp: "2021-06-21T02:29:36Z"
    name: api
    namespace: venus
    resourceVersion: "2380"
    uid: 2872fb18-c6dd-4392-a01c-72391d9a802d
  subsets:
  - addresses:
    - ip: 172.17.0.56
      nodeName: minikube
      targetRef:
        kind: Pod
        name: api-5548866cb5-md92j
        namespace: venus
        resourceVersion: "2367"
        uid: 7bc1b2b7-1201-4911-84d7-cc9b312e8682
    - ip: 172.17.0.64
      nodeName: minikube
      targetRef:
        kind: Pod
        name: api-5548866cb5-b4xq4
        namespace: venus
        resourceVersion: "2378"
        uid: b712599b-e96b-410c-bfcf-475508c8a86d
    ports:
    - name: 2222-80
      port: 80
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    annotations:
      endpoints.kubernetes.io/last-change-trigger-time: "2021-06-21T02:29:55Z"
    creationTimestamp: "2021-06-21T02:29:36Z"
    name: frontend
    namespace: venus
    resourceVersion: "1927"
    uid: daddbd03-170a-4d8c-9bb6-eca0485bc5b1
  subsets:
  - addresses:
    - ip: 172.17.0.57
      nodeName: minikube
      targetRef:
        kind: Pod
        name: frontend-5d5658f9d4-vt9rs
        namespace: venus
        resourceVersion: "1900"
        uid: dc77de93-2a8c-4b05-b3b9-3d1111f99b68
    - ip: 172.17.0.58
      nodeName: minikube
      targetRef:
        kind: Pod
        name: frontend-5d5658f9d4-pvz9k
        namespace: venus
        resourceVersion: "1921"
        uid: 60f26d48-6152-4ccf-82ec-0cea3a856164
    - ip: 172.17.0.59
      nodeName: minikube
      targetRef:
        kind: Pod
        name: frontend-5d5658f9d4-6vssc
        namespace: venus
        resourceVersion: "1894"
        uid: 12ad68c2-f8bb-41d0-9c8a-8698ab383e87
    - ip: 172.17.0.60
      nodeName: minikube
      targetRef:
        kind: Pod
        name: frontend-5d5658f9d4-r4x56
        namespace: venus
        resourceVersion: "1926"
        uid: 7ebfc5d1-54df-44e7-91f8-a1f8c3262065
    - ip: 172.17.0.61
      nodeName: minikube
      targetRef:
        kind: Pod
        name: frontend-5d5658f9d4-dqtng
        namespace: venus
        resourceVersion: "1910"
        uid: bb1cb0bf-5dc0-49f7-8b2f-dea1300781c7
    ports:
    - name: "80"
      port: 80
      protocol: TCP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
