apiVersion: v1
items:
- apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
  kind: PriorityLevelConfiguration
  metadata:
    creationTimestamp: "2021-06-19T05:57:02Z"
    generation: 1
    name: catch-all
    resourceVersion: "74"
    uid: cf217aaa-1300-4d70-9f11-2d54e7699fac
  spec:
    limited:
      assuredConcurrencyShares: 5
      limitResponse:
        type: Reject
    type: Limited
  status: {}
- apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
  kind: PriorityLevelConfiguration
  metadata:
    creationTimestamp: "2021-06-19T05:57:02Z"
    generation: 1
    name: exempt
    resourceVersion: "77"
    uid: bc3e7a6c-cf8d-4065-8768-bac46cbf99e0
  spec:
    type: Exempt
  status: {}
- apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
  kind: PriorityLevelConfiguration
  metadata:
    creationTimestamp: "2021-06-19T05:57:02Z"
    generation: 1
    name: global-default
    resourceVersion: "66"
    uid: 3b7d4e94-1874-425f-af30-55e2d1232593
  spec:
    limited:
      assuredConcurrencyShares: 20
      limitResponse:
        queuing:
          handSize: 6
          queueLengthLimit: 50
          queues: 128
        type: Queue
    type: Limited
  status: {}
- apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
  kind: PriorityLevelConfiguration
  metadata:
    creationTimestamp: "2021-06-19T05:57:02Z"
    generation: 1
    name: leader-election
    resourceVersion: "60"
    uid: 3d31af94-1e70-434e-a886-2420208e47d3
  spec:
    limited:
      assuredConcurrencyShares: 10
      limitResponse:
        queuing:
          handSize: 4
          queueLengthLimit: 50
          queues: 16
        type: Queue
    type: Limited
  status: {}
- apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
  kind: PriorityLevelConfiguration
  metadata:
    creationTimestamp: "2021-06-19T05:57:02Z"
    generation: 1
    name: system
    resourceVersion: "58"
    uid: 456236b5-0379-4b51-9c30-a10b86f058d2
  spec:
    limited:
      assuredConcurrencyShares: 30
      limitResponse:
        queuing:
          handSize: 6
          queueLengthLimit: 50
          queues: 64
        type: Queue
    type: Limited
  status: {}
- apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
  kind: PriorityLevelConfiguration
  metadata:
    creationTimestamp: "2021-06-19T05:57:02Z"
    generation: 1
    name: workload-high
    resourceVersion: "62"
    uid: e46a7071-33d8-4f1a-bdf1-0856e928e989
  spec:
    limited:
      assuredConcurrencyShares: 40
      limitResponse:
        queuing:
          handSize: 6
          queueLengthLimit: 50
          queues: 128
        type: Queue
    type: Limited
  status: {}
- apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
  kind: PriorityLevelConfiguration
  metadata:
    creationTimestamp: "2021-06-19T05:57:02Z"
    generation: 1
    name: workload-low
    resourceVersion: "64"
    uid: 24877ee5-d0b4-4dcb-8bf5-907cca660296
  spec:
    limited:
      assuredConcurrencyShares: 100
      limitResponse:
        queuing:
          handSize: 6
          queueLengthLimit: 50
          queues: 128
        type: Queue
    type: Limited
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
