apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2021-06-19T05:57:03Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "206"
    uid: f75a87a9-5a5b-4daf-9d96-56029308ee52
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-05-11T13:08:05Z","labels":{"id":"earth-2x3-api-svc"},"name":"earth-2x3-api-svc","namespace":"earth","resourceVersion":"2011","uid":"2c646489-2671-4793-bf89-865c994a3c3a"},"spec":{"clusterIP":"10.99.91.205","clusterIPs":["10.99.91.205"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"4546-80","port":4546,"protocol":"TCP","targetPort":80}],"selector":{"id":"earth-2x3-api"},"sessionAffinity":"None","type":"ClusterIP"}}
    creationTimestamp: "2021-06-21T02:29:36Z"
    labels:
      id: earth-2x3-api-svc
    name: earth-2x3-api-svc
    namespace: earth
    resourceVersion: "1316"
    uid: 0c4d4684-25ec-45e5-b321-8f769871af51
  spec:
    clusterIP: 10.99.91.205
    clusterIPs:
    - 10.99.91.205
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 4546-80
      port: 4546
      protocol: TCP
      targetPort: 80
    selector:
      id: earth-2x3-api
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-05-11T13:08:05Z","labels":{"id":"earth-2x3-web-svc"},"name":"earth-2x3-web-svc","namespace":"earth","resourceVersion":"2016","uid":"9a0c8bb3-0ba2-4001-8f28-30fb115ff32f"},"spec":{"clusterIP":"10.101.248.50","clusterIPs":["10.101.248.50"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"4545-80","port":4545,"protocol":"TCP","targetPort":80}],"selector":{"id":"earth-2x3-web"},"sessionAffinity":"None","type":"ClusterIP"}}
    creationTimestamp: "2021-06-21T02:29:36Z"
    labels:
      id: earth-2x3-web-svc
    name: earth-2x3-web-svc
    namespace: earth
    resourceVersion: "1320"
    uid: 54024816-16bf-4b79-8d25-c812a78da13c
  spec:
    clusterIP: 10.101.248.50
    clusterIPs:
    - 10.101.248.50
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 4545-80
      port: 4545
      protocol: TCP
      targetPort: 80
    selector:
      id: earth-2x3-web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-05-11T13:08:05Z","labels":{"id":"earth-3cc-web"},"name":"earth-3cc-web","namespace":"earth","resourceVersion":"2020","uid":"6add02ac-3953-43a1-b567-927afe6a016d"},"spec":{"clusterIP":"10.97.131.47","clusterIPs":["10.97.131.47"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"6363-80","port":6363,"protocol":"TCP","targetPort":80}],"selector":{"id":"earth-3cc-web"},"sessionAffinity":"None","type":"ClusterIP"}}
    creationTimestamp: "2021-06-21T02:29:36Z"
    labels:
      id: earth-3cc-web
    name: earth-3cc-web
    namespace: earth
    resourceVersion: "1324"
    uid: d342f0e4-32a0-4faf-b613-c421772f8064
  spec:
    clusterIP: 10.97.131.47
    clusterIPs:
    - 10.97.131.47
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 6363-80
      port: 6363
      protocol: TCP
      targetPort: 80
    selector:
      id: earth-3cc-web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-05-11T13:08:05Z","name":"jupiter-crew-svc","namespace":"jupiter","resourceVersion":"2024","uid":"5494b07a-11a8-42d1-884a-1efa258262b9"},"spec":{"clusterIP":"10.100.255.41","clusterIPs":["10.100.255.41"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"8080-80","port":8080,"protocol":"TCP","targetPort":80}],"selector":{"id":"jupiter-crew"},"sessionAffinity":"None","type":"ClusterIP"}}
    creationTimestamp: "2021-06-21T02:29:36Z"
    name: jupiter-crew-svc
    namespace: jupiter
    resourceVersion: "1328"
    uid: 258937a4-382c-4bd4-bed3-4d6ca9d7b27b
  spec:
    clusterIP: 10.100.255.41
    clusterIPs:
    - 10.100.255.41
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8080-80
      port: 8080
      protocol: TCP
      targetPort: 80
    selector:
      id: jupiter-crew
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9153"
      prometheus.io/scrape: "true"
    creationTimestamp: "2021-06-19T05:57:04Z"
    labels:
      k8s-app: kube-dns
      kubernetes.io/cluster-service: "true"
      kubernetes.io/name: CoreDNS
    name: kube-dns
    namespace: kube-system
    resourceVersion: "250"
    uid: 148c85af-c4a3-4518-820d-f9c746dd8cf5
  spec:
    clusterIP: 10.96.0.10
    clusterIPs:
    - 10.96.0.10
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
    selector:
      k8s-app: kube-dns
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-05-11T13:08:05Z","labels":{"app":"manager-api-svc"},"name":"manager-api-svc","namespace":"mars","resourceVersion":"2028","uid":"4a03d8f5-9fdf-49e4-8aee-fefcf618c00f"},"spec":{"clusterIP":"10.110.150.253","clusterIPs":["10.110.150.253"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"4444-80","port":4444,"protocol":"TCP","targetPort":80}],"selector":{"id":"manager-api-deployment"},"sessionAffinity":"None","type":"ClusterIP"}}
    creationTimestamp: "2021-06-21T02:29:36Z"
    labels:
      app: manager-api-svc
    name: manager-api-svc
    namespace: mars
    resourceVersion: "1332"
    uid: 78340075-5507-43a9-b21b-72b92f9b7b60
  spec:
    clusterIP: 10.110.150.253
    clusterIPs:
    - 10.110.150.253
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 4444-80
      port: 4444
      protocol: TCP
      targetPort: 80
    selector:
      id: manager-api-deployment
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-05-11T13:08:05Z","name":"api","namespace":"venus","resourceVersion":"2032","uid":"b5125d63-99ab-491e-b1a5-e5c63f6ff32f"},"spec":{"clusterIP":"10.103.197.217","clusterIPs":["10.103.197.217"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"2222-80","port":2222,"protocol":"TCP","targetPort":80}],"selector":{"id":"api"},"sessionAffinity":"None","type":"ClusterIP"}}
    creationTimestamp: "2021-06-21T02:29:36Z"
    name: api
    namespace: venus
    resourceVersion: "1336"
    uid: 095cdb59-a54f-4ebb-9342-4fb8885ec9ee
  spec:
    clusterIP: 10.103.197.217
    clusterIPs:
    - 10.103.197.217
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 2222-80
      port: 2222
      protocol: TCP
      targetPort: 80
    selector:
      id: api
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2021-05-11T13:08:05Z","name":"frontend","namespace":"venus","resourceVersion":"2036","uid":"f8533d79-4288-4c3a-bb81-026ed7034afd"},"spec":{"clusterIP":"10.107.132.162","clusterIPs":["10.107.132.162"],"ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"80","port":80,"protocol":"TCP","targetPort":80}],"selector":{"id":"frontend"},"sessionAffinity":"None","type":"ClusterIP"}}
    creationTimestamp: "2021-06-21T02:29:36Z"
    name: frontend
    namespace: venus
    resourceVersion: "1340"
    uid: 5375d33c-a7bc-4074-bc83-ee80fe8f709d
  spec:
    clusterIP: 10.107.132.162
    clusterIPs:
    - 10.107.132.162
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      id: frontend
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
